src/main/java/com/multi/toonGather/user/testtest.java

240722 1804

---

src/main/java/com/multi/toonGather/config/ContextConfiguration.java
src/main/java/com/multi/toonGather/webtoon/MainController.java
src/main/java/com/multi/toonGather/webtoon/testtest.java
src/main/resources/templates/common/menubar.html
src/main/resources/templates/main/main.html
src/main/resources/templates/webtoon/test.html

Test webtoon

---

src/main/java/com/multi/toonGather/user/controller/testtest.java
src/main/java/com/multi/toonGather/user/model/dao/testtest.java
src/main/java/com/multi/toonGather/user/model/dto/testtest.java
src/main/java/com/multi/toonGather/user/service/testtest.java
src/main/resources/mappers/UserMapper.xml
src/main/resources/templates/user/admin/test.html

-user폴더 하위에 폴더 추가
-*mapper폴더에 UserMapper.xml 추가

[강현구-240723-01] 디렉토리 일부 추가

---

src/main/java/com/multi/toonGather/user/controller/UserController.java
src/main/java/com/multi/toonGather/user/model/dao/UserDAO.java
src/main/java/com/multi/toonGather/user/model/dto/UserDTO.java
src/main/resources/mappers/UserMapper.xml
src/main/resources/templates/common/menubar.html
src/main/resources/templates/user/login.html
src/main/resources/templates/user/mypage.html
src/main/resources/templates/user/signup.html

-user폴더 하위에 파일 추가 및 수정
-*common/menubar.html의 로그인/회원가입/마이페이지 a태그 수정

[강현구-240723-02] 디렉토리 일부 추가

---

src/main/java/com/multi/toonGather/config/MybatisConfig.java
src/main/java/com/multi/toonGather/social/controller/SocialController.java
src/main/java/com/multi/toonGather/social/model/dto/DiaryDTO.java
src/main/java/com/multi/toonGather/social/model/dto/WebtoonDTO.java
src/main/java/com/multi/toonGather/social/model/dto/WriterDTO.java
src/main/java/com/multi/toonGather/social/model/mapper/SocialMapper.java
src/main/java/com/multi/toonGather/social/service/SocialService.java
src/main/java/com/multi/toonGather/social/service/SocialServiceImpl.java
src/main/resources/mappers/social/socialMapper.xml
src/main/resources/templates/social/diaryInsertForm.html
src/main/resources/templates/social/reviewDetail.html
src/main/resources/templates/social/reviewList.html
src/main/resources/templates/social/reviewUpdateForm.html
src/main/resources/templates/social/socialHome.html

[최서윤-240724-02] fix :: 소셜 관련 DTO 수정 및 생성
1. ReviewDTO.java, WriterDTO.java Long 타입을 int로 수정
- 강현구님 UserDTO.java 적용 후 WriterDTO 삭제 예정
2. WebtoonDTO.java 임시 생성
- 박재형님 WebtoonDTO.java 적용 후 WebtoonDTO 삭제 예정
3. DiaryDTO.java 생성
[최서윤-240724-03] fix :: 공통파일(MybatisConfig) 수정
1. '// 서윤 social' 아래 TypeAlias 'diaryDTO' 추가
[최서윤-240724-04] feat :: 리뷰 RUD, 다이어리 C 기능 구현
1. 리뷰 목록 조회: reviewList.html
2. 리뷰 상세 조회: reviewDetail.html
3. 리뷰 수정: reviewUpdateForm.html
4. 리뷰 삭제
5. 다이어리 작성: diaryInsertForm.html
** 미완성: 로그인 사용자 정보 적용, 웹툰 정보 적용, 페이징 처리, 트랜젝션 처리

[최서윤-240725] feat :: feat :: 리뷰 RUD, 다이어리 C 기능 구현

---

src/main/java/com/multi/toonGather/config/MybatisConfig.java

[최서윤-240725-01] fix :: MybatisConfig 수정

[최서윤-240725-01] fix :: MybatisConfig 수정

---

src/main/java/com/multi/toonGather/user/controller/UserController.java
src/main/java/com/multi/toonGather/user/model/mapper/UserMapper.java
src/main/java/com/multi/toonGather/user/service/UserService.java
src/main/java/com/multi/toonGather/user/service/UserServiceImpl.java
src/main/resources/mappers/user/UserMapper.xml
src/main/resources/templates/user/findid.html
src/main/resources/templates/user/findpw.html
src/main/resources/templates/user/idfound.html
src/main/resources/templates/user/insert.html
src/main/resources/templates/user/login.html
src/main/resources/templates/user/signup.html

**[강현구-240726] merge :: ID찾기 일부 구현**
[강현구-240725-01] chore :: html 페이지 추가
-findid.html, findpw.html 추가했습니다
-git pull failed 문제 해결을 위한 커밋입니다
[강현구-240725-02] chore :: idfound.html 추가
-idfound.html 추가했습니다.(Unversioned)
[강현구-240725-03] feat :: ID찾기 구현
-ID찾기 구현했습니다. (KHG10, KHG11)

[강현구-240726] merge :: ID찾기 일부 구현

---

src/main/resources/mappers/social/socialMapper.xml
src/main/resources/templates/social/diaryDetail.html
src/main/resources/templates/social/diaryInsertForm.html
src/main/resources/templates/social/diaryList.html
src/main/resources/templates/social/diaryUpdateForm.html
src/main/resources/templates/social/reviewDetail.html
src/main/resources/templates/social/reviewInsertForm.html
src/main/resources/templates/social/reviewList.html
src/main/resources/templates/social/reviewUpdateForm.html

1. 리뷰/다이어리 해당 웹툰 썸네일 적용
2. 프론트 꾸밈

[최서윤-240726] merge :: 리뷰/다이어리 프론트 수정 머지

---

src/main/java/com/multi/toonGather/webtoon/controller/WebtoonController.java
src/main/java/com/multi/toonGather/webtoon/model/dao/WebToonMapper.java
src/main/java/com/multi/toonGather/webtoon/service/WebToonService.java
src/main/java/com/multi/toonGather/webtoon/service/WebToonServiceImpl.java
src/main/resources/mappers/wt/WebToonMapper.xml
src/main/resources/templates/webtoon/one.html

[박재형 240726-01]미구현
[박재형 240726-02]댓글 조건 추가 및 삭제 기능 구현]

[박재형-240726] merge::댓글 조건 추가 및 삭제 기능 구현 

---

src/main/java/com/multi/toonGather/user/controller/UserController.java
src/main/java/com/multi/toonGather/user/model/mapper/UserMapper.java
src/main/java/com/multi/toonGather/user/service/UserService.java
src/main/java/com/multi/toonGather/user/service/UserServiceImpl.java
src/main/resources/mappers/user/UserMapper.xml
src/main/resources/templates/user/mypage.html
src/main/resources/templates/user/mypage_editprofile.html
src/main/resources/templates/user/pwfound.html

[강현구-240726-01] feat :: PW찾기/마이페이지 회원정보수정
-PW찾기 일부 구현하였습니다.(현재는 PW가 그대로 노출됨)
-마이페이지_프로필수정 GET요청은 완료, POST요청 미완성 상태로 커밋합니다.

[강현구-240726] merge :: PW찾기/마이페이지 회원정보수정

---

src/main/java/com/multi/toonGather/config/MybatisConfig.java
src/main/java/com/multi/toonGather/user/controller/MyController.java
src/main/java/com/multi/toonGather/user/model/dto/MyInEventDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyRctApplicationDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyRctFreeDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MySoDiaryDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MySoReviewDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyWtCommentDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyWtWebtoonDTO.java
src/main/java/com/multi/toonGather/user/model/mapper/MyMapper.java
src/main/java/com/multi/toonGather/user/service/MyService.java
src/main/java/com/multi/toonGather/user/service/MyServiceImpl.java
src/main/resources/mappers/user/MyMapper.xml
src/main/resources/templates/user/admin/userdetails.html
src/main/resources/templates/user/mypage.html
src/main/resources/templates/user/mypage_cs.html
src/main/resources/templates/user/mypage_editprofile.html
src/main/resources/templates/user/mypage_in_event.html
src/main/resources/templates/user/mypage_in_journal.html
src/main/resources/templates/user/mypage_rct_application.html
src/main/resources/templates/user/mypage_rct_free.html
src/main/resources/templates/user/mypage_rct_job.html
src/main/resources/templates/user/mypage_so_diary.html
src/main/resources/templates/user/mypage_so_review.html
src/main/resources/templates/user/mypage_wt_comment.html
src/main/resources/templates/user/mypage_wt_webtoon.html

**[강현구-240801] merge :: 마이페이지-나의웹툰/채용/소식/소셜 구현**
[강현구-240731-02] feat :: 마이페이지-나의소식/나의소셜 구현
-마이페이지_나의 소셜_좋아요한 리뷰 구현했습니다.
-마이페이지_나의 소셜_내가 남긴 다이어리 댓글 구현했습니다.
-마이페이지_나의 소식_좋아요한 행사 구현했습니다.
-build :: MybatisConfig.java에
MySoDiaryDTO, MySoReviewDTO, MyInEventDTO 등록하였음
[강현구-240731-03] feat :: 마이페이지-나의웹툰/나의채용 일부 구현
-마이페이지_나의 웹툰_북마크한 웹툰 구현했습니다.
-마이페이지_나의 웹툰_내가 남긴 코멘트 구현했습니다.
-마이페이지_나의 채용_나의 지원 목록 구현했습니다.
-마이페이지_나의 채용_프리랜서 게시글 관리 구현했습니다.
-build :: MybatisConfig.java에
MyWtWebtoonDTO, MyWtCommentDTO, MyRctApplicationDTO, MyRctFreeDTO 등록하였음

[강현구-240801] merge :: 마이페이지-나의웹툰/채용/소식/소셜 구현

---

src/main/java/com/multi/toonGather/cs/controller/CsController.java
src/main/java/com/multi/toonGather/cs/model/dto/FaqDTO.java
src/main/java/com/multi/toonGather/cs/model/mapper/CsMapper.java
src/main/java/com/multi/toonGather/cs/service/CsService.java
src/main/java/com/multi/toonGather/cs/service/CsServiceImpl.java
src/main/resources/mappers/cs/csMapper.xml
src/main/resources/templates/cs/csAdmin.html
src/main/resources/templates/cs/csUser.html
src/main/resources/templates/cs/faqDetail.html
src/main/resources/templates/cs/insertFaq.html
src/main/resources/templates/cs/updateFaq.html

[김희철-240802-1] feat :: FAQ 조회 기능 구현
- 회원 및 관리자 페이지에서 FAQ 조회 기능 구현
[김희철-240802-2] feat :: FAQ 작성 기능 구현
- 관리자 입장에서 FAQ 작성 기능 구현
[김희철-240802-3] feat :: FAQ 상세조회 기능 구현
- 회원 및 관리자 입장에서 FAQ 상세조회 기능 구현
[김희철-240802-4] feat :: FAQ 수정 기능 구현
- 관리자 입장에서 FAQ 수정 기능 구현
[김희철-240802-5] feat :: FAQ 삭제 기능 구현
- 관리자 입장에서 FAQ 삭제 기능 구현

[김희철-240802] merge :: FAQ CRUD 구현

---

src/main/java/com/multi/toonGather/config/SecurityConfig.java
src/main/java/com/multi/toonGather/user/controller/UserController.java
src/main/java/com/multi/toonGather/user/service/UserService.java
src/main/java/com/multi/toonGather/user/service/UserServiceImpl.java
src/main/resources/mappers/user/UserMapper.xml
src/main/resources/templates/common/menubar.html
src/main/resources/templates/user/admin/userdetails.html
src/main/resources/templates/user/admin/userlist.html
src/main/resources/templates/user/findid.html
src/main/resources/templates/user/findpw.html
src/main/resources/templates/user/login.html
src/main/resources/templates/user/mypage.html
src/main/resources/templates/user/mypage_cs.html
src/main/resources/templates/user/mypage_editprofile.html
src/main/resources/templates/user/mypage_in_event.html
src/main/resources/templates/user/mypage_in_journal.html
src/main/resources/templates/user/mypage_rct_application.html
src/main/resources/templates/user/mypage_rct_free.html
src/main/resources/templates/user/mypage_rct_job.html
src/main/resources/templates/user/mypage_so_diary.html
src/main/resources/templates/user/mypage_so_review.html
src/main/resources/templates/user/mypage_wt_comment.html
src/main/resources/templates/user/mypage_wt_webtoon.html
src/main/resources/templates/user/signup.html

**[강현구-240802] fix :: 일반/관리자 권한, 회원 Validation check 외**
[강현구-240801-01] fix :: 로그인 상태시 메뉴바 수정
-build :: resources/templates/common/menubar.html 수정
(로그인 상태에서 로그아웃 및 마이페이지 표시되도록 개선하였습니다.)
[강현구-240801-02] fix :: 회원 CRUD Validation Check
-관리자에서 회원정보 수정시 권한설정 추가
-Validation Check를 위한 html파일 수정
(현재 전화번호/이메일/생년월일 형식 및 아이디/비밀번호/닉네임 글자수)
-(일반유저 회원정보 수정시) 비밀번호 입력하지 않으면 회원정보 수정 안됨
-build :: SecurityConfig.java
관리자만 접근 가능 (/user/admin/**)
-build :: menubar.html
권한에 따라 (마이페이지/관리자페이지) 보여주기
[강현구-240801-03] fix :: findpw.html 문법오류 수정

[강현구-240802] fix :: 일반/관리자 권한, 회원 Validation check 외

---

.gitignore

**[강현구-240805] merge :: .gitignore 수정**
[강현구-240802-01] build :: .gitignore 수정
-미리 업로드합니다. 감사합니다.

[🟤강현구-240802] merge :: .gitignore 수정

---

src/main/java/com/multi/toonGather/social/model/mapper/SocialMapper.java
src/main/java/com/multi/toonGather/social/service/SocialServiceImpl.java
src/main/resources/mappers/social/SocialMapper.xml
src/main/resources/static/css/social-styles.css
src/main/resources/static/css/styles.css
src/main/resources/templates/common/footer.html
src/main/resources/templates/common/menubar.html
src/main/resources/templates/social/main.html
src/main/resources/templates/social/user/profile.html

[최서윤-240805-01] fix :: 최근 활동 조회 수정
- 웹툰 상세 페이지 연결 링크 수정
[최서윤-240805-02] fix :: 최근 활동 조회 수정 + css 수정
- 다이어리 작성, 다이어리 댓글 등록 활동 표시되도록 수정
- social/main.html, social/user/profile.html css 정비
[최서윤-240805-03] fix :: 검색 기능 수정 (사용자 검색 추가)
[최서윤-240805-04] project :: 푸터 추가 footer.html
-  메뉴바처럼 모두 각자 html 하단에 추가해주세요:<div th:replace="common/footer.html"></div>
- 깃허브 로고 누르면 깃허브 프로젝트 페이지로 이동합니다.
[최서윤-240805-05] chore :: 프론트 작업
- main.html 프론트 완성: 검색 기능 css 수정
[최서윤-240805-06] chore :: 푸터 수정

[최서윤-240806] merge :: 푸터 추가. 소셜 홈, 사용자별 소셜 홈 완성 

---

src/main/java/com/multi/toonGather/config/CurrentUriInterceptor.java
src/main/java/com/multi/toonGather/config/WebMvcConfig.java
src/main/resources/mappers/social/SocialMapper.xml
src/main/resources/static/css/social-styles.css
src/main/resources/static/css/styles.css
src/main/resources/templates/social/diary/detail.html
src/main/resources/templates/social/main.html
src/main/resources/templates/social/review/detail.html
src/main/resources/templates/social/user/diaries.html
src/main/resources/templates/social/user/profile-menubar.html
src/main/resources/templates/social/user/profile.html
src/main/resources/templates/social/user/reviews.html

[최서윤-240806-01] fix :: 최근 활동 오류 해결
- "[닉네임]님의 리뷰/다이어리에 좋아요/댓글"
- 닉네임 클릭하면 해당 리뷰/다이어리 작성자의 툰투게더 프로필 페이지로 잘 이동합니다.
- 나머지 링크도 잘 이동하는 것 확인했습니다.
[최서윤-240806-02] chore :: 리뷰 목록 페이지 프론트 완성
[최서윤-240806-03] project :: 스크롤바 설정, CurrentUriInterceptor 관련 설정 추가
- 페이지 우측에 스크롤바가 고정됩니다.
- 모든 요청에 대해 "HttpServletRequest request"를 "currentUri"로 자동으로 설정하는 인터셉터와 인터셉터 설정 파일을 추가했습니다.
[최서윤-240806-04] chore :: 프론트 작업
- profile-menubar.html 홈/리뷰/다이어리 페이지 이동 시 색 고정 처리
[최서윤-240806-05] fix :: 댓글 작성 오류 해결
- commentsList가 없을 경우 새로 생성 --> 첫 번째 댓글을 추가할 때 "댓글이 없습니다" 메시지 제거 --> 새 댓글을 추가한 후 해당 댓글로 스크롤 하도록 수정
+) 리뷰/다이어리 상세페이지 프론트 작업

[최서윤-240807] merge :: 최근 활동, 댓글 작성 오류 해결, 프론트 작업

---

src/main/java/com/multi/toonGather/common/model/dto/PageNDTO.java

**[강현구-240807] merge :: 마이페이지-검색/페이징**
[강현구-240807-01] PageNDTO.java 누락된 것 추가

[강현구-240807-02] merge :: 마이페이지-검색/페이징

---

src/main/java/com/multi/toonGather/introduction/controller/JournalController.java
src/main/java/com/multi/toonGather/introduction/model/mapper/JournalMapper.java
src/main/java/com/multi/toonGather/introduction/service/JournalService.java
src/main/java/com/multi/toonGather/introduction/service/JournalServiceImpl.java
src/main/resources/mappers/introduction/JournalMapper.xml
src/main/resources/templates/introduction/journal/journalDetail.html
src/main/resources/templates/introduction/journal/journalInsert.html
src/main/resources/templates/introduction/journal/journalUpdate.html
src/main/resources/templates/introduction/journalList.html

[김동현-240806-02] 
feat :: 소식게시판 검색 기능 완료(제목으로 검색)
[김동현-240806-03] 
feat :: 소식게시판 페이징 기능 완료
[김동현-240806-04] 
feat :: 소식게시판 게시글 등록 오류 수정 (첨부파일 없이 등록시 오류)
[김동현-240806-05] 
feat :: 소식게시판 상세페이지 접속 오류 수정 (title으로 해당 게시글을 찾았었는데 같은 제목 존재 시 오류 발생, journalNo로 게시글 찾도록 변경)
[김동현-240806-06] 
fix :: 소식게시판 목록조회페이지에서 radio버튼 정렬 오류 수정
fix :: 수정, 삭제 오류 수정(title으로 해당 게시글을 찾았었는데 같은 제목 존재 시 오류 발생, journalNo로 게시글 찾도록 변경)
feat :: 소식게시판 목록조회페이지 - 검색창 css 수정
[김동현-240806-07] 
fix :: 소식게시판 상세페이지 css 수정

[김동현-240807] merge :: 소식게시판 검색, 페이징, css수정

---

src/main/java/com/multi/toonGather/social/controller/SocialController.java
src/main/java/com/multi/toonGather/social/model/mapper/SocialMapper.java
src/main/java/com/multi/toonGather/social/service/SocialService.java
src/main/java/com/multi/toonGather/social/service/SocialServiceImpl.java
src/main/resources/mappers/social/SocialMapper.xml
src/main/resources/static/css/likeButton.css
src/main/resources/static/css/social-styles.css
src/main/resources/templates/common/footer.html
src/main/resources/templates/social/diary/detail.html
src/main/resources/templates/social/diary/edit.html
src/main/resources/templates/social/diary/insert.html
src/main/resources/templates/social/main.html
src/main/resources/templates/social/review/detail.html
src/main/resources/templates/social/review/edit.html
src/main/resources/templates/social/review/insert.html
src/main/resources/templates/social/user/diaries.html
src/main/resources/templates/social/user/follows.html
src/main/resources/templates/social/user/profile-menubar.html
src/main/resources/templates/social/user/profile.html
src/main/resources/templates/social/user/reviews.html

[최서윤-240807-01] chore :: 프론트 작업
- 리뷰/다이어리 작성/수정 페이지 프론트 완료
- 기타: footer.html 오타, likeButton.css 색 변경
[최서윤-240807-02] chore :: 푸터 페이지 하단에 고정 테스트
- social-styles.css(1~15라인)에 임시로 설정했습니다. 추후에 styles.css에 적용할 예정입니다.
- html 본문에 <메뉴바 div> 본문 <푸터 div> 순서로 있다면 이렇게 적용하면 됩니다:
<메뉴바 div>
<div class="content-wrapper">
본문
</div>
<푸터 div>
[최서윤-240807-03] chore :: <title> 수정
[최서윤-240807-04] feat :: 상세 기능 추가
1. 검색 조건 명시 및 추가
- 리뷰: 제목, 내용, 웹툰 제목으로 검색
- 다이어리: 제목, 내용, 웹툰 제목으로 검색
- 사용자: 닉네임, 아이디, 자기소개로 검색
2. 리뷰 목록 별점 필터 추가
- profile.html '최애 웹툰' 우측의 '모두 보기' 클릭 시 별점 5점 필터 적용된 리뷰 목록 페이지로 이동
3. 리뷰 목록 좋아요순 정렬 추가
- profile.html '인기 리뷰' 우측의 '모두 보기' 클릭 시 좋아요순 정렬 적용된 리뷰 목록 페이지로 이동
4. 리뷰 작성 시 별점 1점 이상 입력하도록 제한
5. profile-menubar.html 자기소개 아래 팔로잉/팔로워 수 추가 (클릭 시 follows.html로 이동)
6. follows.html 팔로잉/팔로워 목록 페이지 추가

[최서윤-240808] merge :: 프론트 작업, 상세 기능 추가

---

src/main/java/com/multi/toonGather/webtoon/controller/WebtoonController.java
src/main/java/com/multi/toonGather/webtoon/model/dao/WebToonMapper.java
src/main/java/com/multi/toonGather/webtoon/service/WebToonService.java
src/main/java/com/multi/toonGather/webtoon/service/WebToonServiceImpl.java
src/main/resources/mappers/wt/WebToonMapper.xml
src/main/resources/templates/webtoon/one.html
src/main/resources/templates/webtoon/webtoonSearch.html
src/main/resources/templates/webtoon/webtoonlist.html

[박재형-240808] merge :: 웹툰 정보 제한 완성,배스트 댓글과 더보기 버튼 완성

---

src/main/java/com/multi/toonGather/cs/controller/CsController.java
src/main/java/com/multi/toonGather/cs/model/mapper/CsMapper.java
src/main/java/com/multi/toonGather/cs/service/CsService.java
src/main/java/com/multi/toonGather/cs/service/CsServiceImpl.java
src/main/resources/mappers/cs/csMapper.xml
src/main/resources/templates/cs/csAdmin.html
src/main/resources/templates/cs/csUser.html
src/main/resources/templates/cs/updateQuestion.html

[김희철-240807-1] feat :: 문의글 수정 시 기존 첨부파일 삭제 기능 구현 중
- 문의글 수정 시 기존 첨부파일 삭제 기능 구현 중 임시 저장
[김희철-240807-2] feat :: 문의글 수정 시 기존 첨부파일 삭제 기능 구현 완료
- 문의글 수정 시 기존 첨부파일 삭제 기능 구현 완료
[김희철-240808-1] fix :: 문의글 검색 기능에 카테고리 검색 추가
- 문의글 검색 기능에 카테고리 검색 추가

[김희철-240808] merge :: 문의글 수정 시 기존 첨부 파일 삭제 기능 및 문의글 카테고리 검색 기능 추가

---

src/main/java/com/multi/toonGather/introduction/controller/EventController.java
src/main/java/com/multi/toonGather/introduction/controller/JournalController.java
src/main/java/com/multi/toonGather/introduction/model/dto/EventCategoryDTO.java
src/main/java/com/multi/toonGather/introduction/model/dto/EventDTO.java
src/main/java/com/multi/toonGather/introduction/model/dto/EventFileDTO.java
src/main/java/com/multi/toonGather/introduction/model/dto/EventLikeDTO.java
src/main/java/com/multi/toonGather/introduction/model/mapper/EventMapper.java
src/main/java/com/multi/toonGather/introduction/service/EventService.java
src/main/java/com/multi/toonGather/introduction/service/EventServiceImpl.java
src/main/resources/mappers/introduction/EventMapper.xml
src/main/resources/templates/introduction/event/eventDetail.html
src/main/resources/templates/introduction/event/eventInsert.html
src/main/resources/templates/introduction/event/eventList.html
src/main/resources/templates/introduction/event/eventUpdate.html
src/main/resources/templates/introduction/journal/journalDetail.html
src/main/resources/templates/introduction/journalList.html

[김동현-240807-01] 
fix :: 소식게시판 목록조회페이지 페이지 오류 수정(게시글 없을때 페이징 버튼이 나타났었음)
feat :: 행사게시판 목록조회페이지, 게시글등록페이지
[김동현-240807-02] 
feat :: 행사게시판 수정페이지, 삭제기능
[김동현-240807-03] 
feat :: 행사게시판 상세페이지 & 좋아요기능

[김동현-240808] merge :: 행사게시판 목록조회, 등록, 수정, 삭제, 상세 페이지

---

src/main/java/com/multi/toonGather/cs/controller/ChatbotController.java
src/main/java/com/multi/toonGather/cs/controller/CsController.java
src/main/java/com/multi/toonGather/cs/service/ChatbotService.java
src/main/java/com/multi/toonGather/cs/service/ChatbotServiceImpl.java
src/main/resources/templates/cs/chatbotPage.html
src/main/resources/templates/cs/csAdmin.html
src/main/resources/templates/cs/csUser.html

[김희철-240810] merge :: 챗봇 연동 완료

---

src/main/java/com/multi/toonGather/introduction/controller/EventController.java
src/main/java/com/multi/toonGather/introduction/model/mapper/EventMapper.java
src/main/java/com/multi/toonGather/introduction/service/EventServiceImpl.java
src/main/resources/mappers/introduction/EventMapper.xml
src/main/resources/templates/introduction/event/eventDetail.html
src/main/resources/templates/introduction/event/eventInsert.html
src/main/resources/templates/introduction/event/eventList.html
src/main/resources/templates/introduction/event/eventUpdate.html

[김동현-240809-01]
fix: 행사 게시판 검색 오류 수정
fix: 행사 게시판 상세 페이지의 CSS 및 JavaScript를 사용하여 페이지 스타일 개선
feat: 행사 게시판 상세 페이지에 카카오 지도 API를 이용해 행사 위치 표시 추가
[김동현-240809-02]
fix: 행사 게시판 상세 페이지 스타일 개선 (내용부분 줄바꿈 오류)

[김동현-240810] merge :: 행사게시판 카카오지도api & 스타일 개선 

---

src/main/java/com/multi/toonGather/user/model/dto/MyRctJobDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyWtCommentDTO.java
src/main/java/com/multi/toonGather/user/model/dto/TimeAgoUtils.java
src/main/resources/mappers/user/MyMapper.xml
src/main/resources/templates/user/admin/userdetails.html
src/main/resources/templates/user/mypage_editprofile.html
src/main/resources/templates/user/mypage_in_event.html
src/main/resources/templates/user/mypage_rct_job.html
src/main/resources/templates/user/mypage_wt_comment.html
src/main/resources/templates/user/mypage_wt_webtoon.html
src/main/resources/templates/user/signup.html

**[강현구-240813] merge :: 프론트작업**
[강현구-240810-01] 프론트 수정
-signup 체크박스 사소한 수정
[강현구-240810-02] 프론트 수정
-회원 입력폼 사소한 수정(필수입력사항 폰트컬러)
[강현구-240811-01] 나의소개-소식
-상세페이지 이동경로 수정
[강현구-240811-02] 프론트-회원 CRUD
-마이페이지_회원정보수정하기 사소한 수정 : placeholder 색상
[강현구-240811-03] feat :: 나의웹툰_내가남긴코멘트
-마이페이지_나의웹툰_내가남긴코멘트 : 댓글남긴시각, 수정된시각 추가
[강현구-240811-04] chore :: 프론트-마이페이지 초벌
-마이페이지 레이아웃 잡는 중(토글있음/토글없음)
[강현구-240812-01] chore :: 프론트-마이페이지 초벌
-(토글있음) 마이페이지 리스트 : 토글제외한 레이아웃 잡음
[강현구-240812-01] chore :: 프론트-마이페이지 초벌
-(토글있음) 마이페이지 리스트 : 페이징 제외한 레이아웃 잡음
-TimeAgoUtils.java : ~일 전/남음 표시하기 위함
[강현구-240812-02] chore :: 프론트-마이페이지 초벌
-(토글있음) 마이페이지 리스트 : 사소한 수정(폰트)
[강현구-240812-03] chore :: 프론트-회원정보 수정
-업로드아이콘 추가
[강현구-240812-04] chore :: 프론트-마이페이지 초벌
-(토글있음) 토글 활성화시 색 변경
[강현구-240812-05] chore :: 프론트-마이페이지 초벌
-(토글있음) 페이징 포함, 사소한 수정 등 …

[강현구-240813] merge :: 프론트작업

---

src/main/java/com/multi/toonGather/webtoon/controller/WebtoonController.java
src/main/java/com/multi/toonGather/webtoon/model/dao/WebToonMapper.java
src/main/java/com/multi/toonGather/webtoon/model/dto/TagPageDTO.java
src/main/java/com/multi/toonGather/webtoon/model/dto/WebtoonDTO.java
src/main/java/com/multi/toonGather/webtoon/service/WebToonService.java
src/main/java/com/multi/toonGather/webtoon/service/WebToonServiceImpl.java
src/main/resources/mappers/wt/WebToonMapper.xml
src/main/resources/templates/webtoon/webtoonSearch.html
src/main/resources/templates/webtoon/webtoonlist.html

[박재형-240814] merge :: 추천 시스템 구현 및 페이지 버튼 수정

---

src/main/java/com/multi/toonGather/user/controller/MyController.java
src/main/java/com/multi/toonGather/user/model/dto/MyCsQuestionDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyInEventDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyInJournalDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyInMerchanDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyInMerchanFileDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyRctApplicationDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyRctFreeDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyRctJobDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyRctOrderDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MySoDiaryDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MySoReviewDTO.java
src/main/java/com/multi/toonGather/user/model/dto/MyWtCommentDTO.java
src/main/java/com/multi/toonGather/user/model/mapper/MyMapper.java
src/main/java/com/multi/toonGather/user/service/MyService.java
src/main/java/com/multi/toonGather/user/service/MyServiceImpl.java
src/main/resources/mappers/user/MyMapper.xml
src/main/resources/templates/user/mypage_cs.html
src/main/resources/templates/user/mypage_in_event.html
src/main/resources/templates/user/mypage_in_journal.html
src/main/resources/templates/user/mypage_in_merchan.html
src/main/resources/templates/user/mypage_rct_application.html
src/main/resources/templates/user/mypage_rct_free.html
src/main/resources/templates/user/mypage_rct_free_orderlist.html
src/main/resources/templates/user/mypage_rct_job_applicationlist.html
src/main/resources/templates/user/mypage_rct_order.html
src/main/resources/templates/user/mypage_so_diary.html
src/main/resources/templates/user/mypage_so_review.html
src/main/resources/templates/user/mypage_wt_comment.html
src/main/resources/templates/user/mypage_wt_webtoon.html

**[강현구-240814] merge :: 프론트작업**
[강현구-240813-01] fix :: 나의채용_내가올린공고
-마이페이지_나의채용_내가올린공고 : 마감기한이 NULL인 경우 미정으로 처리
[강현구-240813-01*] fix :: 프론트작업_나의채용(토글있음)
-마이페이지_나의채용_나의지원서관리
-마이페이지_나의채용_프리랜서구매목록
[강현구-240813-03] fix :: 프론트작업_나의소식(토글있음)
-마이페이지_나의소식_좋아요한행사
EventFileDTO.java(동현님 기존파일)사용
-마이페이지_나의소식_좋아요한굿즈
MyInMerchanFileDTO.java 추가
[강현구-240813-04] fix :: 프론트작업_나의문의(토글있음)
-마이페이지_나의문의
[강현구-240813-05] fix :: 프론트작업_나의소식(토글없음)
-마이페이지_나의소식_좋아요한웹툰소식
[강현구-240813-06] fix :: 프론트작업_나머지(토글없음)
-나의웹툰_북마크한웹툰
-나의웹툰_내가남긴코멘트
-나의소셜_좋아요한리뷰
-나의소셜_내가남긴다이어리댓글
-나의채용_프리랜서게시글관리
[강현구-240813-07] feat :: 프리랜서 게시글 관리-주문목록 추가 외
-(서영님요청) 나의채용_프리랜서게시글관리_주문목록 추가했습니다.
- chore :: 프론트작업 (나의채용_내가올린공고_지원서목록) 일부완료

[강현구-240814] merge :: 프론트작업

---

src/main/resources/templates/common/webtoon_menubar.html

[박재형-240816-02] merge :: 경로 수정 포함

[박재형-240816-02] merge :: 경로 수정 포함

---

src/main/resources/templates/social/diary/detail.html
src/main/resources/templates/social/diary/edit.html
src/main/resources/templates/social/review/edit.html

[최서윤-240814-02] fix :: 리뷰/다이어리 수정페이지 취소 버튼 링크 수정, 댓글 작성 칸 댓글 목록 상단으로 이동
[최서윤-240814-03] fix :: 댓글 JavaScript 유효성 검사 추가, CSS 속성 추가

[최서윤-240816] merge :: 댓글 작성 칸 위치 변경, JavaScript 유효성 검사 추가

---

src/main/resources/templates/cs/faqDetail.html
src/main/resources/templates/cs/questionDetail.html

- 문의글 답변 시 수정 삭제 비활성 및 FAQ 수정일 표시

[김희철-240816] merge :: 문의글 답변 시 수정 삭제 비활성 및 FAQ 수정일 표시

---

src/main/java/com/multi/toonGather/webtoon/controller/WebtoonController.java
src/main/resources/mappers/wt/WebToonMapper.xml
src/main/resources/templates/webtoon/one.html

[박재형-240819] merge :: 통합 시스템 수정

---

src/main/resources/templates/user/findid.html
src/main/resources/templates/user/findpw.html

**[강현구-240819-02] merge :: 통합테스트 대비 보완(2)**
[강현구-240819-01] fix :: ID찾기/PW찾기
-- ID찾기 : 닉네임/이메일 밸리데이션 버그수정2
-- PW찾기 : 아이디/이메일 밸리데이션 버그수정2

[강현구-240819-02] merge :: 통합테스트 대비 보완(2)

---

src/main/resources/templates/cs/csAdmin.html
src/main/resources/templates/cs/updateFaq.html
src/main/resources/templates/cs/updateQuestion.html

[김희철-240819-4] design :: 상태값 검색 기능 위치 변경
- 상태값 검색 기능 위치를 검색 타입의 왼쪽으로 변경
- 문의글 및 FAQ 수정 시에도 공백 입력 제한 적용

[김희철-240820] merge :: 상태값 검색 기능 위치 변경

---

src/main/resources/mappers/user/MyMapper.xml

[[강현구-240823-01] fix :: 나의채용_지원서목록/주문목록]
-- 한 페이지에 뜨는 게시글 수 N=6에서 N=10으로 수정하였습니다.

[강현구-240823] merge :: 나의채용_지원서목록/주문목록
